### Download dos arquivos CSV

Primeiro, vamos baixar os arquivos CSV necessários para o diretório `/content/`.

**Nota:** Se os URLs abaixo não forem os corretos para os seus arquivos, por favor, substitua-os pelos caminhos ou URLs válidos.

In [95]:
# Baixa os arquivos CSV necessários de um repositório público. Por favor, substitua os URLs se os seus arquivos estiverem em outro local.
!wget -q https://raw.githubusercontent.com/gabriellab/datasets/main/ravenstack_accounts.csv -P /content/
!wget -q https://raw.githubusercontent.com/gabriellab/datasets/main/ravenstack_subscriptions.csv -P /content/
!wget -q https://raw.githubusercontent.com/gabriellab/datasets/main/ravenstack_feature_usage.csv -P /content/
!wget -q https://raw.githubusercontent.com/gabriellab/datasets/main/ravenstack_support_tickets.csv -P /content/
!wget -q https://raw.githubusercontent.com/gabriellab/datasets/main/ravenstack_churn_events.csv -P /content/

print("Arquivos baixados para /content/")

Arquivos baixados para /content/

In [96]:
import pandas as pd

# Carrega os dataframes principais a partir dos arquivos CSV no diretório /content/
accounts = pd.read_csv('/content/ravenstack_accounts.csv')
subscriptions = pd.read_csv('/content/ravenstack_subscriptions.csv')
usage = pd.read_csv('/content/ravenstack_feature_usage.csv')
tickets = pd.read_csv('/content/ravenstack_support_tickets.csv')
churn = pd.read_csv('/content/ravenstack_churn_events.csv')

# Exibe as dimensões (número de linhas e colunas) de cada dataframe para uma visão geral
print("Accounts:", accounts.shape)
print("Subscriptions:", subscriptions.shape)
print("Usage:", usage.shape)
print("Tickets:", tickets.shape)
print("Churn:", churn.shape)

Accounts: (500, 10)
Subscriptions: (5000, 14)
Usage: (25000, 8)
Tickets: (2000, 9)
Churn: (600, 9)

In [97]:
# Exibe as primeiras linhas de cada dataframe para uma visualização rápida da estrutura e dos dados.
print("Contas (Accounts):")
display(accounts.head()) # Exibe as 5 primeiras linhas do dataframe de contas

print(
"Assinaturas (Subscriptions):")
display(subscriptions.head()) # Exibe as 5 primeiras linhas do dataframe de assinaturas

print("Uso de Features (Usage):")
display(usage.head()) # Exibe as 5 primeiras linhas do dataframe de uso de features

print("Tickets de Suporte (Tickets):")
display(tickets.head()) # Exibe as 5 primeiras linhas do dataframe de tickets de suporte

print("Eventos de Churn (Churn):")
display(churn.head()) # Exibe as 5 primeiras linhas do dataframe de eventos de churn

Contas (Accounts):

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

Assinaturas (Subscriptions):

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True

Uso de Features (Usage):

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

Tickets de Suporte (Tickets):

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

Eventos de Churn (Churn):

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [98]:
# Lista todas as colunas de cada dataframe para entender a estrutura completa dos dados disponíveis.

print("ACCOUNTS - Colunas:")
print(accounts.columns.tolist()) # Exibe os nomes das colunas do dataframe de contas

print("\nSUBSCRIPTIONS - Colunas:")
print(subscriptions.columns.tolist()) # Exibe os nomes das colunas do dataframe de assinaturas

print("\nUSAGE - Colunas:")
print(usage.columns.tolist()) # Exibe os nomes das colunas do dataframe de uso de features

print("\nTICKETS - Colunas:")
print(tickets.columns.tolist()) # Exibe os nomes das colunas do dataframe de tickets de suporte

print("\nCHURN - Colunas:")
print(churn.columns.tolist()) # Exibe os nomes das colunas do dataframe de eventos de churn

ACCOUNTS - Colunas:
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag']

SUBSCRIPTIONS - Colunas:
['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier', 'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag', 'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag']

USAGE - Colunas:
['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature']

TICKETS - Colunas:
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score', 'escalation_flag']

CHURN - Colunas:
['churn_event_id', 'account_id', 'churn_date', 'reason_code', 'refund_amount_usd', 'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation', 'feedback_text']

In [99]:
# Analisa as distribuições de churn_flag, reason_code, plan_tier e referral_source.

# Exibe a contagem de ocorrências para a flag de churn ('True' para churn, 'False' para retenção) no dataframe de contas.
print("Taxa de churn em accounts:")
print(accounts['churn_flag'].value_counts())

# Exibe a contagem de ocorrências para cada código de motivo de churn no dataframe de churn.
print("\nRazões de churn:")
print(churn['reason_code'].value_counts())

# Exibe a contagem de ocorrências para cada nível de plano ('plan_tier') no dataframe de contas.
print("\nPlanos:")
print(accounts['plan_tier'].value_counts())

# Exibe a contagem de ocorrências para cada fonte de indicação ('referral_source') no dataframe de contas.
print("\nReferral source:")
print(accounts['referral_source'].value_counts())

Taxa de churn em accounts:
churn_flag
False    390
True     110
Name: count, dtype: int64

Razões de churn:
reason_code
features      114
support       104
budget        104
unknown        95
competitor     92
pricing        91
Name: count, dtype: int64

Planos:
plan_tier
Pro           178
Basic         168
Enterprise    154
Name: count, dtype: int64

Referral source:
referral_source
organic    114
other      103
ads         98
event       96
partner     89
Name: count, dtype: int64

In [100]:
# Analisa as distribuições das indústrias e países dos clientes.

# Exibe as 15 indústrias com maior número de contas no dataframe 'accounts'.
print("Indústrias:")
print(accounts['industry'].value_counts().head(15))

# Exibe os 15 países com maior número de contas no dataframe 'accounts'.
print("\nPaíses:")
print(accounts['country'].value_counts().head(15))

Indústrias:
industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79
Name: count, dtype: int64

Países:
country
US    291
UK     58
IN     49
AU     32
DE     25
CA     23
FR     22
Name: count, dtype: int64

In [101]:
# Calcula o número médio de tickets de suporte por conta para churnados vs. retidos.
# Agrupa os tickets por 'account_id' e conta o número de tickets para cada conta.
tickets_por_conta = tickets.groupby('account_id').size().reset_index(name='num_tickets')

# Mescla este resumo com o dataframe 'accounts' para incluir a flag de churn.
accounts_tickets = accounts.merge(
    tickets_por_conta,
    on='account_id',
    how='left'
)

# Preenche valores NaN (que indicam contas sem tickets) com 0.
accounts_tickets['num_tickets'] = accounts_tickets['num_tickets'].fillna(0)

# Calcula a média do número de tickets para contas que churnaram e para as que foram retidas.
print("Média de tickets por conta (churnados vs. retidos):")
display(accounts_tickets.groupby('churn_flag')['num_tickets'].mean())

Média de tickets por conta (churnados vs. retidos):

churn_flag
False    4.020513
True     3.927273
Name: num_tickets, dtype: float64

In [102]:
# Calcula o número médio de escalonamentos por conta para churnados vs. retidos.
# Agrupa os tickets por 'account_id' e soma as flags de escalonamento ('escalation_flag') para cada conta.
escalations = tickets.groupby('account_id')['escalation_flag'].sum().reset_index()

# Mescla este resumo com o dataframe 'accounts' para incluir a flag de churn.
accounts_escalation = accounts.merge(
    escalations,
    on='account_id',
    how='left'
)

# Preenche valores NaN (que indicam contas sem escalonamentos) com 0.
accounts_escalation['escalation_flag'] = accounts_escalation['escalation_flag'].fillna(0)

# Calcula a média do número de escalonamentos para contas que churnaram e para as que foram retidas.
print("Média de escalonamentos por conta (churnados vs. retidos):")
display(accounts_escalation.groupby('churn_flag')['escalation_flag'].mean())

Média de escalonamentos por conta (churnados vs. retidos):

churn_flag
False    0.182051
True     0.218182
Name: escalation_flag, dtype: float64

In [103]:
# Calcula a pontuação média de satisfação por conta para churnados vs. retidos.
# Agrupa os tickets por 'account_id' e calcula a média das pontuações de satisfação ('satisfaction_score') para cada conta.
satisfaction = tickets.groupby('account_id')['satisfaction_score'].mean().reset_index()

# Mescla este resumo com o dataframe 'accounts' para incluir a flag de churn.
accounts_satisfaction = accounts.merge(
    satisfaction,
    on='account_id',
    how='left'
)

# Calcula a média das pontuações de satisfação para contas que churnaram e para as que foram retidas.
print("Média de satisfação por conta (churnados vs. retidos):")
display(accounts_satisfaction.groupby('churn_flag')['satisfaction_score'].mean())

Média de satisfação por conta (churnados vs. retidos):

churn_flag
False    3.953395
True     4.002591
Name: satisfaction_score, dtype: float64

In [104]:
# Analisa o uso de features (contagem, duração, erros, beta) para contas churnadas vs. retidas.

# Agrega o uso por 'subscription_id' para resumir as métricas de uso de cada assinatura.
usage_per_subscription = usage.groupby('subscription_id').agg({
    'usage_count': 'sum',
    'usage_duration_secs': 'sum',
    'error_count': 'sum',
    'is_beta_feature': 'sum' # Soma para identificar se houve uso de feature beta
}).reset_index()

# Mescla o uso por assinatura com as informações da conta (account_id) para associar o uso a cada conta.
usage_accounts = subscriptions[['subscription_id', 'account_id']].merge(
    usage_per_subscription,
    on='subscription_id',
    how='left'
)

# Agrega o uso novamente, mas desta vez por 'account_id', para obter o uso total por conta.
usage_accounts = usage_accounts.groupby('account_id').agg({
    'usage_count': 'sum',
    'usage_duration_secs': 'sum',
    'error_count': 'sum',
    'is_beta_feature': 'sum' # Soma o uso de features beta por conta
}).reset_index()

# Mescla com a flag de churn ('churn_flag') das contas para diferenciar churnados de retidos.
usage_accounts = accounts[['account_id', 'churn_flag']].merge(
    usage_accounts,
    on='account_id',
    how='left'
)

# Preenche valores NaN com 0 para contas que não tiveram uso registrado.
usage_accounts = usage_accounts.fillna(0)

# Calcula a média das métricas de uso (contagem, duração, erros e uso de beta) para contas churnadas e retidas.
print("Média de uso de features (churnados vs. retidos):")
display(usage_accounts.groupby('churn_flag')[[
    'usage_count',
    'usage_duration_secs',
    'error_count',
    'is_beta_feature'
]].mean())

Média de uso de features (churnados vs. retidos):

            usage_count  usage_duration_secs  error_count  is_beta_feature
churn_flag
False        495.130769        150350.879487    28.230769         4.976923
True         522.036364        158347.536364    28.154545         5.481818

In [165]:
# Compara MRR (Receita Recorrente Mensal), ARR (Receita Recorrente Anual), e flags de upgrade/downgrade para contas churnadas vs. retidas.
# Mescla informações de conta (account_id, churn_flag) com dados de assinatura (subscriptions).
accounts_subs = accounts[['account_id','churn_flag']].merge(
    subscriptions,
    on='account_id',
    how='left'
)

# Agrupa por 'churn_flag' e calcula a média das métricas financeiras e de upgrade/downgrade.
print("Média de MRR, ARR, e flags de upgrade/downgrade (churnados vs. retidos):")
display(accounts_subs.groupby('churn_flag_x')[[
    'mrr_amount',
    'arr_amount',
    'upgrade_flag',
    'downgrade_flag'
]].mean())

Média de MRR, ARR, e flags de upgrade/downgrade (churnados vs. retidos):

               mrr_amount    arr_amount  upgrade_flag  downgrade_flag
churn_flag_x
False         2322.518614  27870.223371      0.106774        0.044209
True          2080.605124  24967.261484      0.102473        0.041519

In [106]:
# Calcula a taxa de churn média por frequência de cobrança para entender como o método de pagamento afeta o churn.
print("Taxa de churn por frequência de cobrança:")
display(subscriptions.groupby('billing_frequency')['churn_flag'].mean())

Taxa de churn por frequência de cobrança:

billing_frequency
annual     0.100366
monthly    0.094132
Name: churn_flag, dtype: float64

In [107]:
# Calcula a taxa de churn média por nível de plano ('plan_tier') para identificar quais planos têm maior probabilidade de churn.
print("Taxa de churn por nível de plano:")
display(subscriptions.groupby('plan_tier')['churn_flag'].mean())

Taxa de churn por nível de plano:

plan_tier
Basic         0.094881
Enterprise    0.099826
Pro           0.096716
Name: churn_flag, dtype: float64

In [108]:
# Analisa a relação entre o uso de features beta e a flag de churn para verificar se usuários beta churnam mais ou menos.

# Cria uma coluna 'beta_user' no dataframe `usage_accounts` que é True se a conta usou alguma feature beta (is_beta_feature > 0).
usage_accounts['beta_user'] = usage_accounts['is_beta_feature'] > 0

# Cria uma tabela cruzada para analisar a distribuição de churn de usuários beta vs. não beta.
beta_analysis = usage_accounts.groupby([
    'beta_user',
    'churn_flag'
]).size().unstack(fill_value=0)

print("Análise de churn para usuários beta vs. não beta:")
display(beta_analysis)

Análise de churn para usuários beta vs. não beta:

churn_flag  False  True
beta_user
False           7      1
True          383    109

In [109]:
# Descreve o uso de features beta para contas churnadas e retidas, mostrando estatísticas como média, desvio padrão, etc.
print("Estatísticas de uso de features beta (churnados vs. retidos):")
display(usage_accounts.groupby('churn_flag')['is_beta_feature'].describe())

Estatísticas de uso de features beta (churnados vs. retidos):

            count      mean       std  min  25%  50%  75%   max
churn_flag
False       390.0  4.976923  2.612405  0.0  3.0  5.0  7.0  15.0
True        110.0  5.481818  3.105874  0.0  3.0  5.0  7.0  14.0

In [110]:
# Analisa o uso total de cada feature (por nome da feature) para contas churnadas vs. retidas.

# Seleciona 'account_id' a partir de 'subscription_id' para associar assinaturas a contas.
usage_subs = subscriptions[['subscription_id','account_id']]

# Mescla o dataframe de uso de features com as informações de conta.
usage_features = usage.merge(
    usage_subs,
    on='subscription_id',
    how='left'
)

# Mescla o resultado com a flag de churn das contas para diferenciar churnados de retidos.
usage_features = usage_features.merge(
    accounts[['account_id','churn_flag']],
    on='account_id',
    how='left'
)

# Agrupa por nome da feature e 'churn_flag' para somar o uso de cada feature e ver a distribuição entre churnados e retidos.
print("Uso de features por nome (churnados vs. retidos) - Top 20:")
display(usage_features.groupby([
    'feature_name',
    'churn_flag'
])['usage_count'].sum().unstack(fill_value=0).head(20))

Uso de features por nome (churnados vs. retidos) - Top 20:

churn_flag    False  True
feature_name
feature_1      4708   1656
feature_10     4901   1483
feature_11     4901   1632
feature_12     5244   1290
feature_13     4707   1392
feature_14     4468   1412
feature_15     4926   1695
feature_16     4922   1351
feature_17     4993   1465
feature_18     4522   1328
feature_19     4458   1442
feature_2      5096   1429
feature_20     4903   1638
feature_21     4590   1360
feature_22     4950   1416
feature_23     4559   1042
feature_24     4980   1408
feature_25     4625   1466
feature_26     4891   1579
feature_27     4841   1390

In [111]:
# Conta a frequência de cada feedback de churn, incluindo valores NaN (sem feedback), para entender as razões mais comuns.
print("Frequência dos feedbacks de churn:")
display(churn['feedback_text'].value_counts(dropna=False))

Frequência dos feedbacks de churn:

feedback_text
too expensive             161
missing features          155
NaN                       148
switched to competitor    136
Name: count, dtype: int64

In [112]:
# Mostra os feedbacks de churn por motivo de churn, criando uma categorização mais granular das razões de churn.
print("Feedbacks de churn por motivo de churn:")
display(churn.groupby('reason_code')['feedback_text'].value_counts())

Feedbacks de churn por motivo de churn:

reason_code  feedback_text
budget       too expensive             28
             missing features          24
             switched to competitor    24
competitor   missing features          27
             too expensive             24
             switched to competitor    21
features     too expensive             32
             missing features          27
             switched to competitor    23
pricing      too expensive             25
             switched to competitor    24
             missing features          20
support      missing features          31
             too expensive             29
             switched to competitor    20
unknown      missing features          26
             switched to competitor    24
             too expensive             23
Name: count, dtype: int64

In [113]:
# Agrupa contas por buckets de uso e calcula a taxa de churn para cada bucket, identificando se contas com maior ou menor uso têm mais churn.

# Cria buckets de uso (Baixo, Médio, Alto, Muito Alto) com base nos quartis da contagem de uso.
usage_accounts['usage_bucket'] = pd.qcut(
    usage_accounts['usage_count'],
    q=4,
    labels=['Baixo', 'Médio', 'Alto', 'Muito Alto']
)

# Calcula a taxa de churn para cada bucket de uso.
print("Taxa de churn por bucket de uso:")
display(usage_accounts.groupby('usage_bucket')['churn_flag'].mean())

Taxa de churn por bucket de uso:

/tmp/ipykernel_2653/405712968.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(usage_accounts.groupby('usage_bucket')['churn_flag'].mean())

usage_bucket
Baixo         0.174603
Médio         0.201613
Alto          0.288000
Muito Alto    0.216000
Name: churn_flag, dtype: float64

In [114]:
# Agrupa contas por buckets de erro e calcula a taxa de churn para cada bucket, verificando se a ocorrência de erros afeta o churn.

# Cria buckets de erro (Baixo, Médio, Alto, Muito Alto) com base nos quartis da contagem de erros.
usage_accounts['error_bucket'] = pd.qcut(
    usage_accounts['error_count'],
    q=4,
    labels=['Baixo', 'Médio', 'Alto', 'Muito Alto']
)

# Calcula a taxa de churn para cada bucket de erro.
print("Taxa de churn por bucket de erro:")
display(usage_accounts.groupby('error_bucket')['churn_flag'].mean())

Taxa de churn por bucket de erro:

/tmp/ipykernel_2653/205583946.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(usage_accounts.groupby('error_bucket')['churn_flag'].mean())

error_bucket
Baixo         0.221374
Médio         0.195489
Alto          0.256410
Muito Alto    0.210084
Name: churn_flag, dtype: float64

In [115]:
# Analisa métricas de uso (contagem, duração, erros) com base no feedback de churn.

# Seleciona um resumo das métricas de uso por conta do dataframe `usage_accounts`.
usage_summary = usage_accounts[['account_id',
                                'usage_count',
                                'usage_duration_secs',
                                'error_count']]

# Mescla as informações de churn com o resumo de uso para associar o feedback de churn às métricas de uso.
churn_usage = churn.merge(
    usage_summary,
    on='account_id',
    how='left'
)

# Agrupa por feedback de churn e calcula a média das métricas de uso, ordenando pelo 'usage_count' de forma decrescente.
print("Média de métricas de uso por feedback de churn:")
display(churn_usage.groupby('feedback_text')[
    ['usage_count',
     'usage_duration_secs',
     'error_count']
].mean().sort_values(
    by='usage_count',
    ascending=False
))

Média de métricas de uso por feedback de churn:

                        usage_count  usage_duration_secs  error_count
feedback_text
missing features         515.574194        156710.961290    29.806452
too expensive            497.322981        152894.819876    27.527950
switched to competitor   480.808824        145675.919118    27.632353

In [116]:
# Calcula a taxa de churn média por fonte de indicação, ordenando de forma decrescente para destacar as fontes com maior churn.
print("Taxa de churn por fonte de indicação:")
display(accounts.groupby('referral_source')['churn_flag'].mean().sort_values(ascending=False))

Taxa de churn por fonte de indicação:

referral_source
event      0.302083
other      0.242718
ads        0.234694
organic    0.175439
partner    0.146067
Name: churn_flag, dtype: float64

In [117]:
# Calcula a taxa de churn média por indústria, ordenando de forma decrescente para identificar indústrias mais propensas ao churn.
print("Taxa de churn por indústria:")
display(accounts.groupby('industry')['churn_flag'].mean().sort_values(ascending=False))

Taxa de churn por indústria:

industry
DevTools         0.309735
FinTech          0.223214
HealthTech       0.218750
EdTech           0.164557
Cybersecurity    0.160000
Name: churn_flag, dtype: float64

In [118]:
# Calcula a taxa de churn média por país, ordenando de forma decrescente para identificar países com maior churn.
print("Taxa de churn por país:")
display(accounts.groupby('country')['churn_flag'].mean().sort_values(ascending=False))

Taxa de churn por país:

country
DE    0.320000
US    0.233677
FR    0.227273
IN    0.204082
UK    0.189655
CA    0.173913
AU    0.125000
Name: churn_flag, dtype: float64

In [119]:
# Calcula a taxa de churn média para contas em período de trial vs. não trial, para entender o impacto do trial no churn.
print("Taxa de churn (trial vs. não trial):")
display(accounts.groupby('is_trial')['churn_flag'].mean())

Taxa de churn (trial vs. não trial):

is_trial
False    0.210918
True     0.257732
Name: churn_flag, dtype: float64

In [120]:
# Contagem de contas churnadas/retidas por indústria, mostrando a distribuição do churn em diferentes setores.
print("Contagem de churn por indústria:")
display(accounts.groupby(['industry','churn_flag']).size().unstack(fill_value=0))

Contagem de churn por indústria:

churn_flag     False  True
industry
Cybersecurity     84     16
DevTools          78     35
EdTech            66     13
FinTech           87     25
HealthTech        75     21

In [121]:
# Contagem de contas churnadas/retidas por fonte de indicação, para entender quais canais trazem clientes mais propensos ao churn.
print("Contagem de churn por fonte de indicação:")
display(accounts.groupby(['referral_source','churn_flag']).size().unstack(fill_value=0))

Contagem de churn por fonte de indicação:

churn_flag       False  True
referral_source
ads                 75     23
event               67     29
organic             94     20
other               78     25
partner             76     13

In [122]:
# Analisa o MRR (Receita Recorrente Mensal) e ARR (Receita Recorrente Anual) médios para contas churnadas vs. retidas.

# Seleciona 'account_id' e 'churn_flag' do dataframe 'accounts'.
churn_accounts = accounts[['account_id','churn_flag']]

# Calcula MRR e ARR médios por conta a partir das assinaturas, agrupando por 'account_id'.
account_revenue = subscriptions.groupby('account_id').agg({
    'mrr_amount':'mean',
    'arr_amount':'mean'
}).reset_index()

# Mescla as informações de churn com o resumo de receita por conta.
financial = churn_accounts.merge(
    account_revenue,
    on='account_id',
    how='left'
)

# Calcula a média de MRR e ARR para contas churnadas e retidas.
print("MRR e ARR médios (churnados vs. retidos):")
display(financial.groupby('churn_flag')[[
    'mrr_amount',
    'arr_amount'
]].mean())

MRR e ARR médios (churnados vs. retidos):

             mrr_amount    arr_amount
churn_flag
False       2315.299953  27783.599437
True        2082.922182  24995.066185

In [123]:
# Analisa a taxa de churn, a contagem de contas e o MRR médio por indústria.

# Mescla o dataframe de contas com as informações de receita por conta (MRR, ARR).
churn_by_industry = accounts.merge(
    account_revenue,
    on='account_id',
    how='left'
)

# Agrupa por indústria e calcula a taxa média de churn, a contagem de contas e o MRR médio, ordenando pela taxa de churn decrescente.
print("Análise de churn e receita por indústria:")
display(churn_by_industry.groupby('industry').agg({
    'churn_flag':'mean',
    'account_id':'count',
    'mrr_amount':'mean'
}).sort_values(
    by='churn_flag',
    ascending=False
))

Análise de churn e receita por indústria:

               churn_flag  account_id   mrr_amount
industry
DevTools         0.309735         113  2022.513743
FinTech          0.223214         112  2371.604160
HealthTech       0.218750          96  2112.608242
EdTech           0.164557          79  2587.896865
Cybersecurity    0.160000         100  2306.704593

In [124]:
# Calcula o uso médio de features por indústria.

# Mescla o dataframe de contas com informações de indústria e a contagem total de uso por conta.
accounts_usage = accounts[['account_id','industry']].merge(
    usage_accounts[['account_id','usage_count']],
    on='account_id',
    how='left'
)

# Agrupa por indústria e calcula o uso médio de features, ordenando de forma decrescente.
print("Uso médio de features por indústria:")
display(accounts_usage.groupby('industry')['usage_count'].mean().sort_values(
    ascending=False
))

Uso médio de features por indústria:

industry
DevTools         507.893805
EdTech           506.392405
Cybersecurity    503.720000
FinTech          499.357143
HealthTech       487.791667
Name: usage_count, dtype: float64

### Cruzar Canal de Indicação com Motivo de Churn

Para entender a relação entre o canal de indicação (`referral_source`) e os motivos de churn (`reason_code`), vamos primeiro mesclar os dataframes `accounts` e `churn`.

In [125]:
# Mescla os dataframes 'accounts' e 'churn' para incluir apenas contas que realmente churnaram, utilizando um 'inner merge'.
accounts_churn_merged = accounts.merge(
    churn,
    on='account_id',
    how='inner' # Apenas contas que realmente churnaram
)
print("Primeiras linhas do dataframe mesclado 'accounts_churn_merged':")
display(accounts_churn_merged.head())

Primeiras linhas do dataframe mesclado 'accounts_churn_merged':

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,churn_event_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,C-695fcd,2024-11-23,budget,0.00,False,False,False,switched to competitor
1,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,C-cea92d,2024-12-05,competitor,0.00,True,False,False,NaN
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,C-100b97,2024-10-06,features,0.00,False,False,False,switched to competitor
3,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,C-484fba,2024-12-31,support,62.66,False,True,False,too expensive
4,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,C-109d03,2024-11-08,support,0.00,True,False,False,missing features

Agora, vamos agrupar os dados por `referral_source` e `reason_code` para contar quantas vezes cada combinação ocorre. Isso nos permitirá identificar o principal motivo de churn para cada canal de indicação.

In [126]:
# Agrupa os dados por 'referral_source' e 'reason_code' e conta a ocorrência de cada combinação.
# Isso nos permitirá identificar o principal motivo de churn para cada canal de indicação.
churn_reason_by_referral = accounts_churn_merged.groupby(['referral_source', 'reason_code']).size().unstack(fill_value=0)
print("Ocorrência de motivos de churn por canal de indicação:")
display(churn_reason_by_referral)

Ocorrência de motivos de churn por canal de indicação:

reason_code      budget  competitor  features  pricing  support  unknown
referral_source
ads                  16           7        24       19       16       18
event                21          19        15       21       22       19
organic              26          29        25       17       29       23
other                21          23        32       16       17       14
partner              20          14        18       18       20       21

Finalmente, vamos identificar o principal motivo de churn para cada `referral_source` (canal de indicação) com base nos counts que obtivemos.

In [127]:
# Identifica o motivo de churn mais frequente para cada 'referral_source' (canal de indicação) com base nos counts obtidos.
main_churn_reason_by_referral = churn_reason_by_referral.idxmax(axis=1)
print("Principal motivo de churn por canal de indicação:")
display(main_churn_reason_by_referral)

Principal motivo de churn por canal de indicação:

referral_source
ads          features
event         support
organic    competitor
other        features
partner       unknown
dtype: object

Conforme solicitado, o principal motivo de churn para cada canal de indicação é:

In [128]:
# Exibe novamente o principal motivo de churn por canal de indicação, conforme calculado na etapa anterior.
print("Resultado do principal motivo de churn por canal de indicação:")
display(main_churn_reason_by_referral)

Resultado do principal motivo de churn por canal de indicação:

referral_source
ads          features
event         support
organic    competitor
other        features
partner       unknown
dtype: object

In [129]:
# Analisa a proporção de uso de cada feature por contas que churnaram, para identificar features críticas.

# Prepara dados de uso, mesclando 'subscriptions' para obter 'account_id' e 'accounts' para 'churn_flag'.
usage_subs = subscriptions[['subscription_id', 'account_id']]
usage_features = usage.merge(usage_subs, on='subscription_id', how='left')

usage_features = usage_features.merge(
    accounts[['account_id', 'churn_flag']],
    on='account_id',
    how='left'
)

# Agrupa por feature e calcula o uso total e o uso por contas que churnaram.
feature_churn = usage_features.groupby('feature_name').agg(
    total_usage=('usage_count', 'sum'),
    churned_usage=('usage_count', lambda x: x[usage_features.loc[x.index, 'churn_flag'] == True].sum())
)

# Calcula a parcela do uso total que vem de contas churnadas.
feature_churn['churned_usage_share'] = feature_churn['churned_usage'] / feature_churn['total_usage']

# Exibe as 10 principais features com maior participação de uso por churnados, ordenadas de forma decrescente.
print("Top 10 features com maior participação de uso por contas churnadas:")
display(feature_churn.sort_values('churned_usage_share', ascending=False).head(10))

Top 10 features com maior participação de uso por contas churnadas:

              total_usage  churned_usage  churned_usage_share
feature_name
feature_1            6364           1656             0.260214
feature_4            6374           1646             0.258237
feature_15           6621           1695             0.256004
feature_20           6541           1638             0.250420
feature_11           6533           1632             0.249809
feature_34           6536           1623             0.248317
feature_38           6478           1605             0.247762
feature_19           5900           1442             0.244407
feature_26           6470           1579             0.244049
feature_40           6222           1515             0.243491

In [130]:
# Descreve as estatísticas de uso (usage_count) para contas churnadas vs. retidas, fornecendo um resumo estatístico.
print("Estatísticas de 'usage_count' para contas churnadas vs. retidas:")
display(usage_accounts.groupby('churn_flag')['usage_count'].describe())

Estatísticas de 'usage_count' para contas churnadas vs. retidas:

,count,mean,std,min,25%,50%,75%,max
churn_flag,,,,,,,,
False,390.0,495.130769,172.830454,92.0,366.25,491.0,619.75,1005.0
True,110.0,522.036364,176.474388,171.0,412.25,527.5,616.75,1053.0

In [131]:
# Calcula o uso médio por indústria e status de churn.

# Mescla o dataframe de contas com informações de indústria, 'churn_flag' e 'usage_count' por conta.
accounts_usage = accounts[['account_id','industry','churn_flag']].merge(
    usage_accounts[['account_id','usage_count']],
    on='account_id',
    how='left'
)

# Agrupa por indústria e 'churn_flag', calculando o uso médio de features para cada grupo.
print("Uso médio por indústria e status de churn:")
display(accounts_usage.groupby(['industry','churn_flag'])['usage_count'].mean())

Uso médio por indústria e status de churn:

industry       churn_flag
Cybersecurity  False         494.476190
               True          552.250000
DevTools       False         512.653846
               True          497.285714
EdTech         False         498.878788
               True          544.538462
FinTech        False         488.528736
               True          537.040000
HealthTech     False         482.000000
               True          508.476190
Name: usage_count, dtype: float64

In [132]:
# Analisa a contagem de churns e o MRR total por indústria.

# Mescla o dataframe de contas com as informações de receita por conta.
industry_revenue = accounts.merge(
    account_revenue,
    on='account_id',
    how='left'
)

# Agrupa por indústria e calcula o total de churns (soma de 'churn_flag' onde True=1) e o MRR total.
print("Contagem de churns e MRR total por indústria:")
display(industry_revenue.groupby('industry').agg({
    'churn_flag':'sum',
    'mrr_amount':'sum'
}))

Contagem de churns e MRR total por indústria:

               churn_flag     mrr_amount
industry
Cybersecurity          16  230670.459289
DevTools               35  228544.053000
EdTech                 13  204443.852297
FinTech                25  265619.665916
HealthTech             21  202810.391222

In [133]:
# Calcula a taxa de churn (contagem total, soma de churns e taxa média) por indústria, ordenando pela taxa média de churn.
print("Taxa de churn por indústria (contagem, soma, média):")
display(accounts.groupby('industry')['churn_flag'].agg([
    'count',
    'sum',
    'mean'
]).sort_values('mean', ascending=False))

Taxa de churn por indústria (contagem, soma, média):

               count  sum      mean
industry
DevTools         113   35  0.309735
FinTech          112   25  0.223214
HealthTech        96   21  0.218750
EdTech            79   13  0.164557
Cybersecurity    100   16  0.160000

In [134]:
# Calcula a taxa de churn (contagem total, soma de churns e taxa média) por fonte de indicação, ordenando pela taxa média de churn.
print("Taxa de churn por fonte de indicação (contagem, soma, média):")
display(accounts.groupby('referral_source')['churn_flag'].agg([
    'count',
    'sum',
    'mean'
]).sort_values('mean', ascending=False))

Taxa de churn por fonte de indicação (contagem, soma, média):

                 count  sum      mean
referral_source
event               96   29  0.302083
other              103   25  0.242718
ads                 98   23  0.234694
organic            114   20  0.175439
partner             89   13  0.146067

In [135]:
# Analisa a contagem de churns por mês.

# Converte as colunas de data para o formato datetime para permitir operações de tempo.
churn['churn_date'] = pd.to_datetime(churn['churn_date'])
accounts['signup_date'] = pd.to_datetime(accounts['signup_date'])

# Agrupa os eventos de churn por mês e conta o número de churns em cada mês.
churn_by_month = churn.groupby(churn['churn_date'].dt.to_period('M')).size()

print("Contagem de churns por mês:")
display(churn_by_month)

Contagem de churns por mês:

churn_date
2023-01      1
2023-03      5
2023-04      3
2023-05      3
2023-06      5
2023-07      6
2023-08      7
2023-09      6
2023-10     10
2023-11     11
2023-12     16
2024-01     20
2024-02     10
2024-03     24
2024-04     25
2024-05     27
2024-06     40
2024-07     35
2024-08     42
2024-09     53
2024-10     66
2024-11     68
2024-12    117
Freq: M, dtype: int64

In [136]:
# Calcula a taxa de churn por coorte de mês de signup, para entender o comportamento de churn ao longo do tempo para diferentes grupos de clientes.

# Extrai o mês de signup para cada conta e cria uma nova coluna 'signup_month'.
accounts['signup_month'] = accounts['signup_date'].dt.to_period('M')

# Agrupa por mês de signup e calcula a contagem total de contas e o número de contas churnadas em cada coorte.
cohort_churn = accounts.groupby('signup_month').agg(
    accounts=('account_id', 'count'),
    churned=('churn_flag', 'sum')
)

# Calcula a taxa de churn para cada coorte (contas churnadas / total de contas).
cohort_churn['churn_rate'] = cohort_churn['churned'] / cohort_churn['accounts']

# Exibe as coortes ordenadas por mês de signup para visualizar a tendência.
print("Taxa de churn por coorte de mês de signup:")
display(cohort_churn.sort_values('signup_month'))

Taxa de churn por coorte de mês de signup:

              accounts  churned  churn_rate
signup_month
2023-01             17        4    0.235294
2023-02             18        7    0.388889
2023-03             20        5    0.250000
2023-04             15        3    0.200000
2023-05             26        7    0.269231
2023-06             13        3    0.230769
2023-07             14        3    0.214286
2023-08             16        3    0.187500
2023-09             23        5    0.217391
2023-10             20        7    0.350000
2023-11             25        7    0.280000
2023-12             20        4    0.200000
2024-01             16        3    0.187500
2024-02             13        4    0.307692
2024-03             27        4    0.148148
2024-04             22        5    0.227273
2024-05             22        4    0.181818
2024-06             21        6    0.285714
2024-07             26        3    0.115385
2024-08             21        2    0.095238
2024-09             25        9    0.360000
2024-10             31        7    0.225806
2024-11             32        4    0.125000
2024-12             17        1    0.058824

In [137]:
# Analisa o uso de features nos 90 dias antes do churn para identificar padrões de comportamento de uso que antecedem o churn.

# Converte a coluna 'usage_date' para o formato datetime.
usage['usage_date'] = pd.to_datetime(usage['usage_date'])

# Mescla dados de uso com informações de conta (via 'subscriptions') e churn.
usage_with_account = usage.merge(
    subscriptions[['subscription_id', 'account_id']],
    on='subscription_id',
    how='left'
)

churn_usage_timeline = usage_with_account.merge(
    churn[['account_id', 'churn_date']],
    on='account_id',
    how='inner'
)

# Calcula o número de dias antes do churn para cada registro de uso.
churn_usage_timeline['days_before_churn'] = (
    churn_usage_timeline['churn_date'] - churn_usage_timeline['usage_date']
).dt.days

# Filtra o uso que ocorreu nos 90 dias antes do churn (dias_before_churn entre 0 e 90).
pre_churn_usage = churn_usage_timeline[
    (churn_usage_timeline['days_before_churn'] >= 0) &
    (churn_usage_timeline['days_before_churn'] <= 90)
]

# Soma o 'usage_count' em buckets de 30 dias antes do churn para uma análise agregada.
print("Soma de 'usage_count' em buckets de 30 dias antes do churn:")
display(pre_churn_usage.groupby(
    pd.cut(pre_churn_usage['days_before_churn'], bins=[0, 30, 60, 90], right=False, labels=['0-29 dias', '30-59 dias', '60-89 dias'])
)['usage_count'].sum())

Soma de 'usage_count' em buckets de 30 dias antes do churn:

/tmp/ipykernel_2653/1212055193.py:32: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(pre_churn_usage.groupby(

days_before_churn
0-29 dias     12444
30-59 dias    12081
60-89 dias    12528
Name: usage_count, dtype: int64

In [138]:
# Analisa a amplitude de uso de features (número de features únicas usadas) para contas churnadas vs. retidas.

# Calcula o número de features únicas usadas por cada conta.
feature_breadth = usage_with_account.groupby('account_id')['feature_name'].nunique().reset_index()
feature_breadth.columns = ['account_id', 'unique_features_used']

# Mescla este resumo com o dataframe 'accounts' para incluir a flag de churn.
feature_breadth_accounts = accounts[['account_id', 'churn_flag']].merge(
    feature_breadth,
    on='account_id',
    how='left'
)

# Preenche contas sem uso de features (que não apareceram em `usage_with_account`) com 0.
feature_breadth_accounts['unique_features_used'] = feature_breadth_accounts['unique_features_used'].fillna(0)

# Descreve a amplitude de uso de features para contas churnadas e retidas, fornecendo estatísticas comparativas.
print("Estatísticas da amplitude de uso de features (churnados vs. retidos):")
display(feature_breadth_accounts.groupby('churn_flag')['unique_features_used'].describe())

Estatísticas da amplitude de uso de features (churnados vs. retidos):

            count       mean       std   min    25%   50%   75%   max
churn_flag
False       390.0  27.412821  5.797468   9.0  24.00  28.0  32.0  40.0
True        110.0  28.336364  5.095919  14.0  25.25  29.0  32.0  38.0

In [139]:
# Resumo das métricas de suporte para contas churnadas vs. retidas.

# Converte a coluna 'submitted_at' para o formato datetime.
tickets['submitted_at'] = pd.to_datetime(tickets['submitted_at'])

# Agrega as métricas de suporte por conta, calculando o número de tickets, tempo médio de resolução, tempo médio da primeira resposta, número de escalonamentos e satisfação média.
support_summary = tickets.groupby('account_id').agg(
    tickets=('ticket_id', 'count'),
    avg_resolution_hours=('resolution_time_hours', 'mean'),
    avg_first_response_minutes=('first_response_time_minutes', 'mean'),
    escalations=('escalation_flag', 'sum'),
    avg_satisfaction=('satisfaction_score', 'mean')
).reset_index()

# Mescla este resumo com o dataframe 'accounts' para incluir a flag de churn.
support_accounts = accounts[['account_id', 'churn_flag']].merge(
    support_summary,
    on='account_id',
    how='left'
)

# Calcula a média das métricas de suporte para contas churnadas e retidas para comparação.
print("Média das métricas de suporte (churnados vs. retidos):")
display(support_accounts.groupby('churn_flag')[
    ['tickets', 'avg_resolution_hours', 'avg_first_response_minutes', 'escalations', 'avg_satisfaction']
].mean())

Média das métricas de suporte (churnados vs. retidos):

,tickets,avg_resolution_hours,avg_first_response_minutes,escalations,avg_satisfaction
churn_flag,,,,,
False,4.083333,36.450306,89.581916,0.184896,3.953395
True,4.000000,35.485483,84.926947,0.222222,4.002591

In [140]:
# Prepara o dataframe para modelagem (englobando várias métricas e one-hot encoding).

# Mescla o dataframe 'accounts' com a amplitude de features ('feature_breadth'), o resumo de suporte ('support_summary') e a receita por conta ('account_revenue').
model_df = accounts.merge(feature_breadth, on='account_id', how='left')
model_df = model_df.merge(support_summary, on='account_id', how='left')
model_df = model_df.merge(account_revenue, on='account_id', how='left')

# Preenche valores ausentes (NaN) com 0, assumindo que a ausência de dados significa zero ocorrência ou valor.
model_df = model_df.fillna(0)

# Aplica One-Hot Encoding para variáveis categóricas ('industry', 'referral_source', 'plan_tier', 'country'), criando novas colunas binárias e removendo a coluna original para evitar multicolinearidade.
model_df = pd.get_dummies(
    model_df,
    columns=['industry', 'referral_source', 'plan_tier', 'country'],
    drop_first=True
)

print("Primeiras linhas do dataframe preparado para modelagem:")
display(model_df.head())

Primeiras linhas do dataframe preparado para modelagem:

,account_id,account_name,signup_date,seats,is_trial,churn_flag,signup_month,unique_features_used,tickets,avg_resolution_hours,...,referral_source_other,referral_source_partner,plan_tier_Enterprise,plan_tier_Pro,country_CA,country_DE,country_FR,country_IN,country_UK,country_US
0,A-2e4581,Company_0,2024-10-16,9,False,False,2024-10,27,2.0,23.000000,...,False,True,False,False,False,False,False,False,False,True
1,A-43a9e3,Company_1,2023-08-17,18,False,True,2023-08,23,3.0,38.000000,...,True,False,False,False,False,False,False,True,False,False
2,A-0a282f,Company_2,2024-08-27,1,False,False,2024-08,34,3.0,43.666667,...,False,False,False,False,False,False,False,False,False,True
3,A-1f0ac7,Company_3,2023-08-27,24,True,False,2023-08,26,2.0,29.000000,...,True,False,False,False,False,False,False,False,True,False
4,A-ce550d,Company_4,2024-10-27,35,False,True,2024-10,32,7.0,42.285714,...,False,False,True,False,False,False,False,False,False,True

In [141]:
# Analisa a contagem de churn por mês e indústria.

# Mescla as informações de churn com os atributos da conta (indústria, fonte de indicação).
churn_accounts = churn.merge(
    accounts[['account_id', 'industry', 'referral_source']],
    on='account_id',
    how='left'
)

# Extrai o mês da data de churn e cria uma nova coluna 'churn_month'.
churn_accounts['churn_month'] = churn_accounts['churn_date'].dt.to_period('M')

# Cria uma tabela cruzada de churn por mês e indústria, preenchendo valores ausentes com 0.
churn_by_month_industry = churn_accounts.groupby(
    ['churn_month', 'industry']
).size().unstack(fill_value=0)

print("Últimas 6 linhas da contagem de churn por mês e indústria:")
display(churn_by_month_industry.tail(6))

Últimas 6 linhas da contagem de churn por mês e indústria:

industry     Cybersecurity  DevTools  EdTech  FinTech  HealthTech
churn_month
2024-07                  2        12      10        4           7
2024-08                  4        14      11        6           7
2024-09                 12        10       8       13          10
2024-10                  9        15      12       22           8
2024-11                 16        11      12       11          18
2024-12                 26        29      15       28          19

In [142]:
# Analisa a contagem de churn por mês e canal de indicação.

# Cria uma tabela cruzada de churn por mês e canal de indicação, preenchendo valores ausentes com 0.
churn_by_month_source = churn_accounts.groupby(
    ['churn_month', 'referral_source']
).size().unstack(fill_value=0)

print("Últimas 6 linhas da contagem de churn por mês e canal de indicação:")
display(churn_by_month_source.tail(6))

Últimas 6 linhas da contagem de churn por mês e canal de indicação:

referral_source  ads  event  organic  other  partner
churn_month
2024-07            3     10       13      3        6
2024-08            8      9       10      8        7
2024-09           10      8       17      8       10
2024-10           11     13       18     10       14
2024-11            8     10       19     18       13
2024-12           17     29       28     23       20

In [143]:
# Analisa a tendência temporal dos motivos de churn.

# Extrai o mês da data de churn e cria uma nova coluna 'churn_month' (se já não existir).
churn['churn_month'] = churn['churn_date'].dt.to_period('M')

# Cria uma tabela cruzada de churn por mês e motivo, preenchendo valores ausentes com 0.
churn_reason_time = churn.groupby(
    ['churn_month', 'reason_code']
).size().unstack(fill_value=0)

print("Últimas 12 linhas da tendência temporal dos motivos de churn:")
display(churn_reason_time.tail(12))

Últimas 12 linhas da tendência temporal dos motivos de churn:

reason_code  budget  competitor  features  pricing  support  unknown
churn_month
2024-01           3           1         6        4        3        3
2024-02           2           3         2        3        0        0
2024-03           2           2         6        4        5        5
2024-04           4           3         6        7        1        4
2024-05           5           7         3        3        7        2
2024-06           7          10         7        5        7        4
2024-07           6           5         4        6        6        8
2024-08           6           8         9        7        7        5
2024-09          11           7         8        9        9        9
2024-10          11          12        13        8       10       12
2024-11          10           6        16       15       10       11
2024-12          26          15        24       10       21       21

In [144]:
# Analisa a tendência temporal dos feedbacks de churn.

# Cria uma tabela cruzada de churn por mês e feedback, preenchendo valores ausentes com 0.
churn_feedback_time = churn.groupby(
    ['churn_month', 'feedback_text']
).size().unstack(fill_value=0)

print("Últimas 12 linhas da tendência temporal dos feedbacks de churn:")
display(churn_feedback_time.tail(12))

Últimas 12 linhas da tendência temporal dos feedbacks de churn:

feedback_text  missing features  switched to competitor  too expensive
churn_month
2024-01                       6                       5              6
2024-02                       1                       1              4
2024-03                      10                       3              4
2024-04                       6                      10              5
2024-05                       9                       4              5
2024-06                      14                       4             14
2024-07                       9                       8              8
2024-08                      11                       8             10
2024-09                      10                      16             17
2024-10                       9                      21             17
2024-11                      19                      18             16
2024-12                      26                      23             35

In [145]:
# Verifica a unicidade de 'account_id' no dataframe 'churn' e compara com o número total de eventos de churn.
# Retorna o número de IDs de contas únicas e o número total de linhas (eventos) no dataframe 'churn'.
print("Número de contas únicas que churnaram e total de eventos de churn:")
display(churn['account_id'].nunique(), churn.shape[0])

Número de contas únicas que churnaram e total de eventos de churn:

352

600

In [146]:
# Descreve a distribuição da contagem de churns por 'account_id'.
# Agrupa os eventos de churn por 'account_id' e exibe estatísticas descritivas (média, min, max, etc.) da frequência de churn por conta.
print("Estatísticas descritivas da contagem de churns por conta:")
display(churn.groupby('account_id').size().describe())

Estatísticas descritivas da contagem de churns por conta:

count    352.000000
mean       1.704545
std        0.846095
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
dtype: float64

In [147]:
# Exibe as 20 contas com mais eventos de churn.
# Agrupa os eventos de churn por 'account_id', conta a ocorrência de cada um, ordena de forma decrescente e mostra as 20 maiores.
print("Top 20 contas com mais eventos de churn:")
display(churn.groupby('account_id').size().sort_values(ascending=False).head(20))

Top 20 contas com mais eventos de churn:

account_id
A-0a62f5    5
A-180abf    5
A-ee42db    4
A-0baac2    4
A-0cc442    4
A-ae052e    4
A-37f969    4
A-425e76    4
A-68f37c    4
A-fd7ad3    4
A-9208f0    4
A-533452    4
A-104f1a    3
A-e83938    3
A-e888d1    3
A-e19ff6    3
A-e51ec7    3
A-e351e1    3
A-5a184f    3
A-96bbc6    3
dtype: int64

In [148]:
# Calcula a taxa de churn mensal ao longo do tempo.

# Converte as colunas 'start_date' e 'end_date' em 'subscriptions' para o formato datetime.
subscriptions['start_date'] = pd.to_datetime(subscriptions['start_date'])
subscriptions['end_date'] = pd.to_datetime(subscriptions['end_date'])

# Define o intervalo de meses a serem analisados, do início da primeira assinatura até o último evento de churn.
months = pd.period_range(
    subscriptions['start_date'].min().to_period('M'),
    churn['churn_date'].max().to_period('M'),
    freq='M'
)

monthly_active = []

# Itera por cada mês para calcular o número de contas ativas e churnadas.
for month in months:
    month_start = month.to_timestamp()
    month_end = month.to_timestamp(how='end')

    # Contas ativas no mês: aquelas que começaram antes ou no final do mês E (não terminaram OU terminaram depois ou no início do mês).
    active = subscriptions[
        (subscriptions['start_date'] <= month_end) &
        ((subscriptions['end_date'].isna()) | (subscriptions['end_date'] >= month_start))
    ]['account_id'].nunique()

    # Contas churnadas no mês: aquelas cujo evento de churn ocorreu neste mês.
    churned = churn[churn['churn_date'].dt.to_period('M') == month]['account_id'].nunique()

    monthly_active.append({
        'month': month,
        'active_accounts': active,
        'churned_accounts': churned,
        'churn_rate': churned / active if active > 0 else 0 # Calcula a taxa de churn.
    })

# Cria um dataframe com as taxas de churn mensais e exibe as últimas 12 linhas.
monthly_churn_rate = pd.DataFrame(monthly_active)
print("Últimas 12 linhas da taxa de churn mensal ao longo do tempo:")
display(monthly_churn_rate.tail(12))

Últimas 12 linhas da taxa de churn mensal ao longo do tempo:

      month  active_accounts  churned_accounts  churn_rate
12  2024-01              217                18    0.082949
13  2024-02              235                10    0.042553
14  2024-03              260                24    0.092308
15  2024-04              282                23    0.081560
16  2024-05              310                25    0.080645
17  2024-06              337                38    0.112760
18  2024-07              365                33    0.090411
19  2024-08              385                40    0.103896
20  2024-09              416                48    0.115385
21  2024-10              439                60    0.136674
22  2024-11              475                60    0.126316
23  2024-12              500                96    0.192000

In [149]:
# Cria uma tabela cruzada entre a fonte de indicação ('referral_source') e a indústria ('industry') para entender as combinações.
print("Tabela cruzada: Fonte de Indicação vs. Indústria:")
display(pd.crosstab(accounts['referral_source'], accounts['industry']))

Tabela cruzada: Fonte de Indicação vs. Indústria:

industry         Cybersecurity  DevTools  EdTech  FinTech  HealthTech
referral_source
ads                         17        26      15       22          18
event                       22        23       9       26          16
organic                     21        24      18       20          31
other                       20        24      17       25          17
partner                     20        16      20       19          14

In [150]:
# Cria uma tabela cruzada normalizada por linha para ver a distribuição de indústrias por fonte de indicação.
# Os valores representam a proporção de cada indústria dentro de cada fonte de indicação.
print("Tabela cruzada normalizada por linha: Distribuição de Indústrias por Fonte de Indicação:")
display(pd.crosstab(
    accounts['referral_source'],
    accounts['industry'],
    normalize='index'
))

Tabela cruzada normalizada por linha: Distribuição de Indústrias por Fonte de Indicação:

industry         Cybersecurity  DevTools    EdTech   FinTech  HealthTech
referral_source
ads                   0.173469  0.265306  0.153061  0.224490    0.183673
event                 0.229167  0.239583  0.093750  0.270833    0.166667
organic               0.184211  0.210526  0.157895  0.175439    0.271930
other                 0.194175  0.233010  0.165049  0.242718    0.165049
partner               0.224719  0.179775  0.224719  0.213483    0.157303

In [151]:
# Analisa as contas que churnaram por 'muito caro' (too expensive), agrupadas por indústria e MRR médio.

# Mescla o dataframe 'churn' com informações da conta ('accounts') e receita por conta ('account_revenue').
churn_accounts_full = churn.merge(
    accounts[['account_id','industry','referral_source','plan_tier']],
    on='account_id',
    how='left'
).merge(
    account_revenue,
    on='account_id',
    how='left'
)

# Filtra as contas cujo feedback de churn foi 'too expensive'.
too_expensive = churn_accounts_full[churn_accounts_full['feedback_text'] == 'too expensive']

# Agrupa por indústria e calcula a contagem de contas e o MRR médio para aquelas que churnaram por serem 'muito caro', ordenando pela contagem decrescente.
print("Análise de churn por 'muito caro' (Indústria e MRR Médio):")
display(too_expensive.groupby('industry').agg(
    count=('account_id','count'),
    avg_mrr=('mrr_amount','mean')
).sort_values('count', ascending=False))

Análise de churn por 'muito caro' (Indústria e MRR Médio):

               count      avg_mrr
industry
FinTech           39  1944.177622
DevTools          36  1750.918708
Cybersecurity     34  2209.788129
EdTech            26  2946.655104
HealthTech        26  2888.513034

In [152]:
# Analisa as contas que churnaram por 'muito caro' (too expensive), agrupadas por plano ('plan_tier') e MRR médio.
print("Análise de churn por 'muito caro' (Plano e MRR Médio):")
display(too_expensive.groupby('plan_tier').agg(
    count=('account_id','count'),
    avg_mrr=('mrr_amount','mean')
).sort_values('count', ascending=False))

Análise de churn por 'muito caro' (Plano e MRR Médio):

            count      avg_mrr
plan_tier
Pro            62  2273.286582
Enterprise     58  2298.348197
Basic          41  2230.614762

In [153]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Define as features (variáveis independentes) para o modelo de machine learning, excluindo IDs e datas.
features = [
    col for col in model_df.columns
    if col not in ['account_id','account_name','signup_date','signup_month','churn_flag']
]

X = model_df[features] # Variáveis independentes para o modelo.
y = model_df['churn_flag'].astype(int) # Variável dependente (target), convertida para inteiro (0 ou 1).

# Divide os dados em conjuntos de treino (75%) e teste (25%), mantendo a proporção da variável 'churn_flag' em ambos os conjuntos (stratify=y).
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# Cria um pipeline para o modelo: primeiro, escala os dados usando StandardScaler, e depois aplica a Regressão Logística.
model = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(max_iter=1000)) # Define o número máximo de iterações para convergência.
])

# Treina o modelo usando os dados de treino.
model.fit(X_train, y_train)

# Calcula as probabilidades de previsão de churn no conjunto de teste. O `[:, 1]` seleciona a probabilidade da classe positiva (churn).
pred_proba = model.predict_proba(X_test)[:, 1]

# Avalia o modelo usando a métrica ROC-AUC (Receiver Operating Characteristic - Area Under the Curve).
print("ROC-AUC:", roc_auc_score(y_test, pred_proba))

# Exibe um relatório de classificação detalhado, incluindo precisão, recall, f1-score e suporte.
print("\nRelatório de Classificação:")
print(classification_report(y_test, model.predict(X_test)))

ROC-AUC: 0.611111111111111

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.79      0.99      0.88        98
           1       0.50      0.04      0.07        27

    accuracy                           0.78       125
   macro avg       0.64      0.51      0.47       125
weighted avg       0.73      0.78      0.70       125

In [154]:
# Exibe os coeficientes do modelo de regressão logística para entender a importância e a direção de impacto de cada feature.

# Cria um dataframe com as features e seus respectivos coeficientes, ordenando pelos coeficientes de forma decrescente.
coefs = pd.DataFrame({
    'feature': features,
    'coefficient': model.named_steps['logreg'].coef_[0]
}).sort_values('coefficient', ascending=False)

print("Top 15 features por coeficiente do modelo de regressão logística:")
display(coefs.head(15))

Top 15 features por coeficiente do modelo de regressão logística:

                  feature  coefficient
25             country_US     0.466543
21             country_DE     0.334455
10      industry_DevTools     0.307371
22             country_FR     0.263420
14  referral_source_event     0.227368
23             country_IN     0.215318
24             country_UK     0.186889
2    unique_features_used     0.171307
13    industry_HealthTech     0.160405
20             country_CA     0.138462
16  referral_source_other     0.122816
12       industry_FinTech     0.094413
1                is_trial     0.081069
0                   seats     0.036686
6             escalations     0.026302

In [155]:
# Calcula a taxa de churn média por país, ordenando de forma decrescente para identificar quais países têm maior taxa de churn.
print("Taxa de churn por país:")
display(accounts.groupby("country")["churn_flag"].mean().sort_values(ascending=False))

Taxa de churn por país:

country
DE    0.320000
US    0.233677
FR    0.227273
IN    0.204082
UK    0.189655
CA    0.173913
AU    0.125000
Name: churn_flag, dtype: float64

In [164]:
# Contagem de contas e contas churnadas por país.
# Agrupa por país e calcula o número total de contas e o número de contas que churnaram.
print("Contagem de contas e contas churnadas por país:")
display(accounts.groupby("country").agg(
    contas=("account_id","count"),
    churnados=("churn_flag","sum")
))

Contagem de contas e contas churnadas por país:

         contas  churnados
country
AU           32          4
CA           23          4
DE           25          8
FR           22          5
IN           49         10
UK           58         11
US          291         68

In [157]:
# Calcula o número médio de assentos ('seats') e a taxa de churn por país.
# Agrupa por país e calcula a média de assentos e a taxa de churn ('churn_flag' média).
print("Média de assentos e taxa de churn por país:")
display(accounts.groupby("country").agg(
    avg_seats=("seats","mean"),
    churn_rate=("churn_flag", "mean")
))

Média de assentos e taxa de churn por país:

         avg_seats  churn_rate
country
AU       24.812500    0.125000
CA       25.695652    0.173913
DE       13.040000    0.320000
FR       25.090909    0.227273
IN       22.673469    0.204082
UK       18.000000    0.189655
US       20.144330    0.233677

In [158]:
# Conta o número de contas que vieram da fonte de indicação 'event'.
# Filtra o dataframe 'accounts' para incluir apenas as contas com 'referral_source' igual a 'event'.
event_accounts = accounts[
    accounts["referral_source"] == "event"
]

print("Número de contas vindas da fonte de indicação 'event':", event_accounts.shape[0])

Número de contas vindas da fonte de indicação 'event': 96

In [159]:
# Exibe os IDs das contas que vieram da fonte de indicação 'event'.
print("IDs das contas vindas da fonte de indicação 'event':")
display(event_accounts["account_id"])

IDs das contas vindas da fonte de indicação 'event':

4      A-ce550d
8      A-7dacce
17     A-ce66f8
19     A-832ec2
24     A-9f2731
         ...
467    A-a2485e
473    A-4a4c2d
484    A-e1b9cd
487    A-ac9111
490    A-d3c88e
Name: account_id, Length: 96, dtype: object

In [160]:
# Encontra as 10 contas FinTech com maior MRR (Receita Recorrente Mensal).

# Mescla o dataframe 'accounts' com as informações de receita por conta ('account_revenue').
merged = accounts.merge(account_revenue, on='account_id', how='left')

# Filtra as contas que pertencem à indústria 'FinTech'.
fintech_accounts = merged[
    merged["industry"] == "FinTech"
]

# Ordena as contas FinTech por MRR em ordem decrescente e exibe as 10 maiores.
print("Top 10 contas FinTech com maior MRR:")
display(fintech_accounts[
    ["account_id","mrr_amount"]
].sort_values(
    "mrr_amount",
    ascending=False
).head(10))

Top 10 contas FinTech com maior MRR:

    account_id    mrr_amount
403   A-d4e0d4  13806.000000
475   A-e08cd3   6456.363636
341   A-09316c   6363.636364
281   A-1f7acb   5864.000000
174   A-fa3095   5769.166667
399   A-2d1036   4973.307692
108   A-2e3bad   4587.200000
11    A-d40bf7   4324.700000
40    A-05f0e5   4259.083333
64    A-7e0a10   4111.600000

In [161]:
# Calcula o MRR médio para contas que vieram da fonte de indicação 'event'.
# Filtra o dataframe 'merged' para incluir apenas as contas com 'referral_source' igual a 'event'.
event_accounts = merged[
    merged["referral_source"] == "event"
]

# Calcula e exibe o MRR médio para essas contas.
print("MRR médio para contas da fonte de indicação 'event':", event_accounts["mrr_amount"].mean())

MRR médio para contas da fonte de indicação 'event': 2137.95019059355

In [163]:
# Exemplo de cálculo numérico isolado, provavelmente para demonstração ou verificação rápida.
96 * (0.302083 - 0.22)

7.879967999999999

In [162]:
# Calcula o MRR médio para contas da indústria 'DevTools'.
# Filtra o dataframe 'merged' para incluir apenas as contas com 'industry' igual a 'DevTools'.
devtools = merged[
    merged["industry"] == "DevTools"
]

# Calcula e exibe o MRR médio para essas contas.
print("MRR médio para contas da indústria 'DevTools':", devtools["mrr_amount"].mean())

MRR médio para contas da indústria 'DevTools': 2022.5137433608672